### ISSUE TITLE
README points to an out-of-date zipfile

### ISSUE THREAD

**Issue by JackDanger** [jaykz52/mechanic#17]
Plenty of good, recent code is missing from the official release. How about releasing a new version?

**Comment by jaykz52** [comment]
Good call. I've been off the grid with this project for a while. I've been putting the polish on a 1.0 for one of my other OS projects, and plan to show this mechanic some love starting this month. Will get this up-to-date this morning.

**Comment by jaykz52** [comment]
@JackDanger I've built and uploaded the latest to my personal site and linked from there (in light of the removal of Github Files). If you'd like to confirm, that'd be great. Thanks!

**Comment by JackDanger** [comment]
Works great! Thanks.
