### ISSUE TITLE
README.md mistake re mechanic.js

### ISSUE THREAD

**Issue by bernfarr** [jaykz52/mechanic#20]
In the **Including Mechanic.js** section of the READEME.md file it says I just include `mechanic.js` to use mechanic features. But there is no mechanic.js file in the src directory. Am I missing something?

I assume the contents of `mechanic.js` should be:
    #import "mechanic-core.js"
    #import "data.js"
    #import "events.js"
    #import "logging.js"

Note that `data.js` depends on mechanic from `mechanic-core.js` being defined.

**Comment by jaykz52** [comment]
Hi @bernfarr, The source doesn't include the distributable, which is basically just the modules concated together. If you've got rake, you can run `rake`, which will build mechanic.js under the `dist` directory.

There's also a download link in the README, which is probably easier.
