### ISSUE TITLE
Is $() recursive?

### ISSUE THREAD

**Issue by bernfarr** [jaykz52/mechanic#21]
If I'm looking for the UIAButton in the following structure

```
  UIAWindow
    UIATableView
      UIATableCell
         UIAButton: name:edit
```

will `$('#edit')` return the correct element? I'm digging through the code (rusty JS coder) and it's not clear that this would work.

**Comment by jaykz52** [comment]
`$("#edit")` will find that button. The underlying method that is invoked will do a tree search for all elements whose name is "edit." Take a look at https://github.com/jaykz52/mechanic/blob/master/src/mechanic-core.js#L140 for a better picture
