### ISSUE TITLE
Tapping an element shows "(null).tap()" in the log

### ISSUE THREAD

**Issue by phatmann** [jaykz52/mechanic#26]
The Appium folks made [a fix](https://github.com/appium/appium/commit/502466d28598ac518084b96e14f23633225aa359#app/uiauto/lib/mechanic.js) for this. I verified that it works.

**Comment by jaykz52** [comment]
@phatmann can you submit a pull request with this change? Otherwise, I'll just pull the changes later tonight.

**Comment by phatmann** [comment]
Done.
