### ISSUE TITLE
Error on line 67 of mechanic.js

### ISSUE THREAD

**Issue by stefanpearson** [jaykz52/mechanic#30]
The script breaks immediately, even when just importing it, does anyone else have this issue?

```
Error: Script threw an uncaught JavaScript error: 'undefined' is not a function (evaluating 'typeShortcuts[key].forEach(function(shortcut) { typeSelectorREString += shortcut + "|"; })') on line 67 of mechanic.js
```

**Comment by jodonnell** [comment]
I also get this error.  Fixed by adding

```
            if (key=='dumpProperties' || key=='getMethods') continue;
```

at line 66

**Comment by jaykz52** [comment]
Oh, interesting. Sorry about that! Will take a look.

**Comment by jaykz52** [comment]
@stefanpearson @jodonnell I'm not getting a Javascript error when running against latest mechanic in master. What version of XCode are you using?

**Comment by jodonnell** [comment]
Not at computer now but as far as I know it's the latest. Definitely 5 something. As you can tell from my comment for whatever reason 2 elements magically were added to the object

**Comment by slevin** [comment]
same issue here @jodonnell fix above worked for me. It seems like the newest UIAutomation javascript runtime might insert some extra "convenience" items into the Object (Using Xcode 5)

**Comment by jaykz52** [comment]
Should be fixed by @slevin's PR. Reopen if not!
