### ISSUE TITLE
iOS8 beta breaks mechanic

### ISSUE THREAD

**Issue by jlipps** [jaykz52/mechanic#36]
This simple script fails:

``` js
#import /Users/saucelabs/Desktop/mechanic.js
$.log("foo");
```

Looks like `#import` no longer puts everything into the same scope?

**Comment by jlipps** [comment]
or perhaps apple has just done away with `#import` and is ignoring it

**Comment by ingshtrom** [comment]
I've heard of other's having similar issues with the `#import` statement in Xcode 6.  I don't think it is a mechanic problem.

**Comment by jlipps** [comment]
yeah, looks like they removed it.
